//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aneejian.PowerPoint.Downsizer.AddIn.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ribbon_ShowDownsizerTab {
            get {
                return ((bool)(this["Ribbon_ShowDownsizerTab"]));
            }
            set {
                this["Ribbon_ShowDownsizerTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Ribbon_ShowCoffeeButton {
            get {
                return ((bool)(this["Ribbon_ShowCoffeeButton"]));
            }
            set {
                this["Ribbon_ShowCoffeeButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ulong Stat_UsageCounter {
            get {
                return ((ulong)(this["Stat_UsageCounter"]));
            }
            set {
                this["Stat_UsageCounter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Coffee_AlreadyBought {
            get {
                return ((bool)(this["Coffee_AlreadyBought"]));
            }
            set {
                this["Coffee_AlreadyBought"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint Coffee_HiddenSinceCounter {
            get {
                return ((uint)(this["Coffee_HiddenSinceCounter"]));
            }
            set {
                this["Coffee_HiddenSinceCounter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Coffee_HideCounter {
            get {
                return ((int)(this["Coffee_HideCounter"]));
            }
            set {
                this["Coffee_HideCounter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Ribbon_ShowUpdateButton {
            get {
                return ((bool)(this["Ribbon_ShowUpdateButton"]));
            }
            set {
                this["Ribbon_ShowUpdateButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Update_FilePath {
            get {
                return ((string)(this["Update_FilePath"]));
            }
            set {
                this["Update_FilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ulong Stat_LayoutsDeleted {
            get {
                return ((ulong)(this["Stat_LayoutsDeleted"]));
            }
            set {
                this["Stat_LayoutsDeleted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ulong Stat_MastersDeleted {
            get {
                return ((ulong)(this["Stat_MastersDeleted"]));
            }
            set {
                this["Stat_MastersDeleted"] = value;
            }
        }
    }
}
